CREATE TABLE delivery_address_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street VARCHAR(255) NOT NULL,
    postcode VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL
);

CREATE TABLE customer_entity (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255) NOT NULL,
    company_email VARCHAR(255) NOT NULL,
    duns_number BIGINT NOT NULL,
    company_address_id BIGINT
);

ALTER TABLE customer_entity ADD CONSTRAINT fk_customer_entity_company_address_id FOREIGN KEY (company_address_id) REFERENCES delivery_address_entity(id);

CREATE TABLE order_entity (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date DATE NOT NULL,
    desired_shipping_date DATE NOT NULL,
    order_status VARCHAR(255) NOT NULL,
    order_value DOUBLE PRECISION NOT NULL,
    customer_id BIGINT,
    shipping_address_id BIGINT,
    billing_address_id BIGINT
);

ALTER TABLE order_entity ADD CONSTRAINT fk_order_entity_customer_id FOREIGN KEY (customer_id) REFERENCES customer_entity(customer_id);

ALTER TABLE order_entity ADD CONSTRAINT fk_order_entity_shipping_address_id FOREIGN KEY (shipping_address_id) REFERENCES delivery_address_entity(id);

ALTER TABLE order_entity ADD CONSTRAINT fk_order_entity_billing_address_id FOREIGN KEY (billing_address_id) REFERENCES delivery_address_entity(id);

CREATE TABLE product_entity (
    product_number BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    product_category VARCHAR(255) NOT NULL
);

CREATE TABLE order_line_entity (
    line_number BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity BIGINT NOT NULL,
    unit VARCHAR(255) NOT NULL,
    unit_price DOUBLE PRECISION NOT NULL,
    currency VARCHAR(255) NOT NULL,
    order_id BIGINT,
    product_id BIGINT
);

ALTER TABLE order_line_entity ADD CONSTRAINT fk_order_line_entity_order_id FOREIGN KEY (order_id) REFERENCES order_entity(order_id);

ALTER TABLE order_line_entity ADD CONSTRAINT fk_order_line_entity_product_id FOREIGN KEY (product_id) REFERENCES product_entity(product_number);

CREATE TABLE price_list_entry_entity (
    ple_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price DOUBLE PRECISION NOT NULL,
    currency VARCHAR(255) NOT NULL,
    product_id BIGINT
);

ALTER TABLE price_list_entry_entity ADD CONSTRAINT fk_price_list_entry_entity_product_id FOREIGN KEY (product_id) REFERENCES product_entity(product_number);

CREATE TABLE warehouse_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE warehouse_item_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    current_stock BIGINT NOT NULL,
    unit VARCHAR(255) NOT NULL,
    minimum_stock_level BIGINT NOT NULL,
    product_id BIGINT,
    products_in_stock_id BIGINT
);

ALTER TABLE warehouse_item_entity ADD CONSTRAINT fk_warehouse_item_entity_product_id FOREIGN KEY (product_id) REFERENCES product_entity(product_number);

ALTER TABLE warehouse_item_entity ADD CONSTRAINT fk_warehouse_item_entity_products_in_stock_id FOREIGN KEY (products_in_stock_id) REFERENCES warehouse_entity(id);
