// @generated by Moproco
import { test, expect } from '@playwright/test';

test.describe('ListOpenOrders', () => {
  test('should render OrdersList', async ({ page }) => {
    await page.goto('/orders');
    await expect(page.locator('h1')).toHaveText('OrdersList');
    await expect(page.locator('table')).toBeVisible();
    await expect(page.locator('thead th').first()).toHaveText('Order ID');
  });

});
