// @generated by Moproco
import { test, expect } from '@playwright/test';

test.describe('GetOrdersDetails', () => {
  test('should render OrderDetails', async ({ page }) => {
    await page.goto('/orders/1');
    await expect(page.locator('h1')).toHaveText('OrderDetails');
    await expect(page.locator('table')).toBeVisible();
    await expect(page.locator('thead th').first()).toHaveText('Order ID');
  });

});
